openapi: 3.0.0
info:
  title: Profile Service
  description: Manages user profiles, preferences, and account settings.
  x-cortex-tag: profile-service
  x-cortex-type: service
  x-cortex-groups:
    - web-applications
  x-cortex-owners:
    - type: group
      name: cortex-workshops/web-team
      provider: GITHUB
  x-cortex-git:
    github:
      alias: cortex
      repository: cortex-workshops/profile-service
  x-cortex-issues:
    jira:
      labels:
        - name: web
